/*
 RequireJS Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.3
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Oct 14 23:10:06 2010 -0400
*/
var require,define;
(function(){function O(k){return Ca.call(k)==="[object Function]"}function G(k,m){va.apply(x,k);m.loaded[k[0]]=true}function ka(k,m,s){var r,w,z;for(r=0;z=m[r];r++){z=typeof z==="string"?{name:z}:z;w=z.location;if(s&&(!w||w.indexOf("/")!==0&&w.indexOf(":")===-1))z.location=s+"/"+(z.location||z.name);z.location=z.location||z.name;z.lib=z.lib||"lib";z.main=z.main||"main";k[z.name]=z}}function ra(k){var m=true,s=k.config.priorityWait,r,w;if(s){for(w=0;r=s[w];w++)if(!k.loaded[r]){m=false;break}m&&delete k.config.priorityWait}return m}
function oa(k){var m,s=E.paused;if(k.scriptCount<=0){for(k.scriptCount=0;pa.length;){m=pa.shift();m[0]===null?x.onError(new Error("Mismatched anonymous require.def modules")):G(m,k)}if(!(k.config.priorityWait&&!ra(k))){if(s.length)for(k=0;m=s[k];k++)x.checkDeps.apply(x,m);x.checkLoaded(E.ctxName)}}}function Da(k,m){if(!k.jQuery)if((m=m||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in m){k.jQuery=m;if(!k.defined.jquery&&!k.jQueryDef)k.defined.jquery=m;if(k.scriptCount){m.readyWait+=1;k.jQueryIncremented=
true}}}function sa(k){return function(m){k.exports=m}}function la(k,m,s){return function(){var r=[].concat(Ea.call(arguments,0));r.push(m,s);return(k?require[k]:require).apply(null,r)}}function Fa(k,m){var s=k.contextName,r=la(null,s,m);x.mixin(r,{modify:la("modify",s,m),def:la("def",s,m),get:la("get",s,m),nameToUrl:la("nameToUrl",s,m),ready:x.ready,context:k,config:k.config,isBrowser:E.isBrowser});return r}var ca={},E,Z,ma=[],qa,da,wa,ia,A,c={},xa,Ma=/^(complete|loaded)$/,Ga=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,
ya=/require\(["']([\w-_\.\/]+)["']\)/g,va,ea=!!(typeof window!=="undefined"&&navigator&&document),Ha=!ea&&typeof importScripts!=="undefined",Ca=Object.prototype.toString,Ia=Array.prototype,Ea=Ia.slice,na,x,ta,pa=[],Ja=false,za;if(typeof require!=="undefined")if(O(require))return;else c=require;x=require=function(k,m,s,r,w){var z;if(typeof k==="string"&&!O(m))return require.get(k,m,s,r);if(!require.isArray(k)){z=k;if(require.isArray(m)){k=m;m=s;s=r;r=w}else k=[]}va(null,k,m,z,s,r);(k=E.contexts[s||
z&&z.context||E.ctxName])&&k.scriptCount===0&&oa(k)};x.onError=function(k){throw k;};define=x.def=function(k,m,s,r){var w,z,F=za;if(typeof k!=="string"){r=s;s=m;m=k;k=null}if(!x.isArray(m)){r=s;s=m;m=[]}if(!k&&!m.length&&x.isFunction(s)){s.toString().replace(Ga,"").replace(ya,function(J,Q){m.push(Q)});m=["require","exports","module"].concat(m)}if(!k&&Ja){w=document.getElementsByTagName("script");for(k=w.length-1;k>-1&&(z=w[k]);k--)if(z.readyState==="interactive"){F=z;break}F||x.onError(new Error("ERROR: No matching script interactive for "+
s));k=F.getAttribute("data-requiremodule")}if(typeof k==="string")E.contexts[E.ctxName].jQueryDef=k==="jquery";pa.push([k,m,s,null,r])};va=function(k,m,s,r,w,z){var F,J,Q,P;w=w?w:r&&r.context?r.context:E.ctxName;F=E.contexts[w];if(k){J=F.waiting[k];if(F&&(F.defined[k]||J&&J!==Ia[k]))return}if(w!==E.ctxName){J=E.contexts[E.ctxName]&&E.contexts[E.ctxName].loaded;Q=true;if(J)for(P in J)if(!(P in ca))if(!J[P]){Q=false;break}if(Q)E.ctxName=w}if(!F){F={contextName:w,config:{waitSeconds:7,baseUrl:E.baseUrl||
"./",paths:{},packages:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{},scriptCount:0,urlFetched:{},defPlugin:{},defined:{},modifiers:{}};F=E.contexts[w]=F}if(r){if(r.baseUrl)if(r.baseUrl.charAt(r.baseUrl.length-1)!=="/")r.baseUrl+="/";Q=F.config.paths;J=F.config.packages;x.mixin(F.config,r,true);if(r.paths){for(P in r.paths)P in ca||(Q[P]=r.paths[P]);F.config.paths=Q}if((Q=r.packagePaths)||r.packages){if(Q)for(P in Q)P in ca||ka(J,Q[P],P);r.packages&&ka(J,r.packages);F.config.packages=
J}if(r.priority){x(r.priority);F.config.priorityWait=r.priority}if(r.deps||r.callback)x(r.deps||[],r.callback);r.ready&&x.ready(r.ready);if(!m)return}if(m){P=m;m=[];for(r=0;r<P.length;r++)m[r]=x.splitPrefix(P[r],k||z,F)}z=F.waiting.push({name:k,deps:m,callback:s});if(k){F.waiting[k]=z-1;F.specified[k]=true;if(z=F.modifiers[k]){x(z,w);if(z=z.__deferMods)for(r=0;r<z.length;r++){P=z[r];J=P[P.length-1];if(J===undefined)P[P.length-1]=w;else typeof J==="string"&&z.push(w);require.def.apply(require,P)}}}if(k&&
s&&!x.isFunction(s))F.defined[k]=s;E.paused.push([void 0,k,m,F]);if(k){F.loaded[k]=true;F.jQueryDef=k==="jquery"}};x.mixin=function(k,m,s){for(var r in m)if(!(r in ca)&&(!(r in k)||s))k[r]=m[r];return x};x.version="0.14.5";E=x.s={ctxName:"_",contexts:{},paused:[],skipAsync:{},isBrowser:ea,isPageLoaded:!ea,readyCalls:[],doc:ea?document:null};x.isBrowser=E.isBrowser;if(ea){E.head=document.getElementsByTagName("head")[0];if(ta=document.getElementsByTagName("base")[0])E.head=ta.parentNode}x.completeLoad=
function(k,m){for(var s;pa.length;){s=pa.shift();if(s[0]===null){s[0]=k;break}else if(s[0]===k)break;else G(s,m)}s&&G(s,m);m.loaded[k]=true;Da(m);m.scriptCount-=1;oa(m)};x.pause=x.resume=function(){};x.checkDeps=function(k,m,s,r){if(!k)for(k=0;m=s[k];k++)if(!r.specified[m.fullName]){r.specified[m.fullName]=true;r.startTime=(new Date).getTime();m.prefix||x.load(m.name,r.contextName)}};x.modify=function(k,m,s,r,w){var z,F,J=(typeof k==="string"?w:m)||E.ctxName,Q=E.contexts[J],P=Q.modifiers;if(typeof k===
"string"){F=P[k]||(P[k]=[]);if(!F[m]){F.push(m);F[m]=true}Q.specified[k]?x.def(m,s,r,w):(F.__deferMods||(F.__deferMods=[])).push([m,s,r,w])}else for(z in k)if(!(z in ca)){m=k[z];F=P[z]||(Q.modifiers[z]=[]);if(!F[m]){F.push(m);F[m]=true;Q.specified[z]&&x([m],J)}}};x.isArray=function(k){return Ca.call(k)==="[object Array]"};x.isFunction=O;x.get=function(k,m,s){if(k==="require"||k==="exports"||k==="module")x.onError(new Error("Explicit require of "+k+" is not allowed."));m=m||E.ctxName;var r=E.contexts[m];
k=x.normalizeName(k,s,r);s=r.defined[k];s===undefined&&x.onError(new Error("require: module name '"+k+"' has not been loaded yet for context: "+m));return s};x.load=function(k,m){var s=E.contexts[m],r=s.urlFetched,w=s.loaded;E.isDone=false;w[k]||(w[k]=false);if(m!==E.ctxName)ma.push(arguments);else{w=x.nameToUrl(k,null,m);if(!r[w]){s.scriptCount+=1;x.attach(w,m,k);r[w]=true;if(s.jQuery&&!s.jQueryIncremented){s.jQuery.readyWait+=1;s.jQueryIncremented=true}}}};x.jsExtRegExp=/\.js$/;x.normalizeName=
function(k,m,s){if(k.charAt(0)==="."){m||x.onError(new Error("Cannot normalize module name: "+k+", no relative module name available."));if(s.config.packages[m])m=[m];else{m=m.split("/");m=m.slice(0,m.length-1)}k=m.concat(k.split("/"));for(Z=0;m=k[Z];Z++)if(m==="."){k.splice(Z,1);Z-=1}else if(m===".."){k.splice(Z-1,2);Z-=2}k=k.join("/")}return k};x.splitPrefix=function(k,m,s){var r=k.indexOf("!"),w=null;if(r!==-1){w=k.substring(0,r);k=k.substring(r+1,k.length)}k=x.normalizeName(k,m,s);return{prefix:w,
name:k,fullName:w?w+"!"+k:k}};x.nameToUrl=function(k,m,s,r){var w,z,F,J;J=E.contexts[s];s=J.config;k=x.normalizeName(k,r,J);if(k.indexOf(":")!==-1||k.charAt(0)==="/"||x.jsExtRegExp.test(k))k=k+(m?m:"");else{w=s.paths;z=s.packages;r=k.split("/");for(J=r.length;J>0;J--){F=r.slice(0,J).join("/");if(w[F]){r.splice(0,J,w[F]);break}else if(F=z[F]){w=F.location+"/"+F.lib;if(k===F.name)w+="/"+F.main;r.splice(0,J,w);break}}k=r.join("/")+(m||".js");k=(k.charAt(0)==="/"||k.match(/^\w+:/)?"":s.baseUrl)+k}return s.urlArgs?
k+((k.indexOf("?")===-1?"?":"&")+s.urlArgs):k};x.checkLoaded=function(k){var m=E.contexts[k||E.ctxName],s=m.config.waitSeconds*1E3,r=s&&m.startTime+s<(new Date).getTime(),w,z=m.defined,F=m.modifiers,J="",Q=false,P=false,V;if(!m.isCheckLoaded){if(m.config.priorityWait)if(ra(m))oa(m);else return;m.isCheckLoaded=true;s=m.waiting;w=m.loaded;for(V in w)if(!(V in ca)){Q=true;if(!w[V])if(r)J+=V+" ";else{P=true;break}}if(!Q&&!s.length)m.isCheckLoaded=false;else{if(r&&J){w=new Error("require.js load timeout for modules: "+
J);w.requireType="timeout";w.requireModules=J;x.onError(w)}if(P){m.isCheckLoaded=false;if(ea||Ha)setTimeout(function(){x.checkLoaded(k)},50)}else{m.waiting=[];m.loaded={};for(V in F)V in ca||z[V]&&x.execModifiers(V,{},s,m);for(w=0;z=s[w];w++)x.exec(z,{},s,m);m.isCheckLoaded=false;if(m.waiting.length)x.checkLoaded(k);else if(ma.length){w=m.loaded;m=true;for(V in w)if(!(V in ca))if(!w[V]){m=false;break}if(m){E.ctxName=ma[0][1];V=ma;ma=[];for(w=0;m=V[w];w++)x.load.apply(x,m)}}else{E.ctxName="_";E.isDone=
true;x.callReady&&x.callReady()}}}}};x.exec=function(k,m,s,r){if(k){var w=k.name,z=k.callback;z=k.deps;var F,J,Q=r.defined,P,V=[],ha,Aa=false;if(w){if(m[w]||w in Q)return Q[w];m[w]=true}if(z)for(F=0;J=z[F];F++){J=J.name;if(J==="require")J=Fa(r,w);else if(J==="exports"){J=Q[w]={};Aa=true}else if(J==="module"){ha=J={id:w,uri:w?x.nameToUrl(w,null,r.contextName):undefined};ha.setExports=sa(ha)}else J=J in Q?Q[J]:m[J]?undefined:x.exec(s[s[J]],m,s,r);V.push(J)}if((z=k.callback)&&x.isFunction(z)){P=x.execCb(w,
z,V);if(w)if(Aa&&P===undefined&&(!ha||!("exports"in ha)))P=Q[w];else if(ha&&"exports"in ha)P=Q[w]=ha.exports;else{w in Q&&!Aa&&x.onError(new Error(w+" has already been defined"));Q[w]=P}}x.execModifiers(w,m,s,r);return P}};x.execCb=function(k,m,s){return m.apply(null,s)};x.execModifiers=function(k,m,s,r){var w=r.modifiers,z=w[k],F,J;if(z){for(J=0;J<z.length;J++){F=z[J];F in s&&x.exec(s[s[F]],m,s,r)}delete w[k]}};x.onScriptLoad=function(k){var m=k.currentTarget||k.srcElement,s;if(k.type==="load"||
Ma.test(m.readyState)){s=m.getAttribute("data-requirecontext");k=m.getAttribute("data-requiremodule");s=E.contexts[s];x.completeLoad(k,s);m.removeEventListener?m.removeEventListener("load",x.onScriptLoad,false):m.detachEvent("onreadystatechange",x.onScriptLoad)}};x.attach=function(k,m,s,r,w){var z;if(ea){r=r||x.onScriptLoad;z=document.createElement("script");z.type=w||"text/javascript";z.charset="utf-8";if(!E.skipAsync[k])z.async=true;z.setAttribute("data-requirecontext",m);z.setAttribute("data-requiremodule",
s);if(z.addEventListener)z.addEventListener("load",r,false);else{Ja=true;z.attachEvent("onreadystatechange",r)}z.src=k;za=z;ta?E.head.insertBefore(z,ta):E.head.appendChild(z);za=null;return z}else if(Ha){r=E.contexts[m];m=r.loaded;m[s]=false;importScripts(k);x.completeLoad(s,r)}return null};E.baseUrl=c.baseUrl;if(ea&&(!E.baseUrl||!E.head)){qa=document.getElementsByTagName("script");wa=c.baseUrlMatch?c.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(Z=qa.length-1;Z>-1&&
(da=qa[Z]);Z--){if(!E.head)E.head=da.parentNode;if(!c.deps)if(ia=da.getAttribute("data-main"))c.deps=[ia];if((ia=da.src)&&!E.baseUrl)if(A=ia.match(wa)){E.baseUrl=ia.substring(0,A.index);break}}}x.pageLoaded=function(){if(!E.isPageLoaded){E.isPageLoaded=true;na&&clearInterval(na);if(xa)document.readyState="complete";x.callReady()}};x.callReady=function(){var k=E.readyCalls,m,s,r;if(E.isPageLoaded&&E.isDone){if(k.length){E.readyCalls=[];for(m=0;s=k[m];m++)s()}k=E.contexts;for(r in k)if(!(r in ca)){m=
k[r];if(m.jQueryIncremented){m.jQuery.readyWait-=1;m.jQueryIncremented=false}}}};x.ready=function(k){E.isPageLoaded&&E.isDone?k():E.readyCalls.push(k);return x};if(ea){if(document.addEventListener){document.addEventListener("DOMContentLoaded",x.pageLoaded,false);window.addEventListener("load",x.pageLoaded,false);if(!document.readyState){xa=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",x.pageLoaded);if(self===self.top)na=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");
x.pageLoaded()}}catch(k){}},30)}document.readyState==="complete"&&x.pageLoaded()}x(c);typeof setTimeout!=="undefined"&&setTimeout(function(){var k=E.contexts[c.context||"_"];Da(k);oa(k)},0)})();
(function(O,G){function ka(){return false}function ra(){return true}function oa(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function Da(a){var b,d,e=[],g=[],h,l,n,p,y,B,K,L;l=c.data(this,this.nodeType?"events":"__events__");if(typeof l==="function")l=l.events;if(!(a.liveFired===this||!l||!l.live||a.button&&a.type==="click")){if(a.namespace)L=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var S=l.live.slice(0);for(p=0;p<S.length;p++){l=S[p];l.origType.replace(na,
"")===a.type?g.push(l.selector):S.splice(p--,1)}g=c(a.target).closest(g,a.currentTarget);y=0;for(B=g.length;y<B;y++){K=g[y];for(p=0;p<S.length;p++){l=S[p];if(K.selector===l.selector&&(!L||L.test(l.namespace))){n=K.elem;h=null;if(l.preType==="mouseenter"||l.preType==="mouseleave"){a.type=l.preType;h=c(a.relatedTarget).closest(l.selector)[0]}if(!h||h!==n)e.push({elem:n,handleObj:l,level:K.level})}}}y=0;for(B=e.length;y<B;y++){g=e[y];if(d&&g.level>d)break;a.currentTarget=g.elem;a.data=g.handleObj.data;
a.handleObj=g.handleObj;L=g.handleObj.origHandler.apply(g.elem,arguments);if(L===false||a.isPropagationStopped()){d=g.level;if(L===false)b=false}}return b}}function sa(a,b){return(a&&a!=="*"?a+".":"")+b.replace(ta,"`").replace(pa,"&")}function la(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function Fa(a,b,d){if(c.isFunction(b))return c.grep(a,function(g,h){return!!b.call(g,h,g)===d});else if(b.nodeType)return c.grep(a,function(g){return g===b===d});else if(typeof b==="string"){var e=c.grep(a,
function(g){return g.nodeType===1});if(V.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(g){return c.inArray(g,b)>=0===d})}function ca(a){return c.nodeName(a,"table")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function E(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),g=c.data(this,e);if(e=e&&e.events){delete g.handle;g.events={};for(var h in e)for(var l in e[h])c.event.add(this,
h,e[h][l],e[h][l].data)}}})}function Z(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function ma(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?$a:ab,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function qa(a,
b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(g,h){d||bb.test(a)?e(a,h):qa(a+"["+(typeof h==="object"||c.isArray(h)?g:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?e(a,""):c.each(b,function(g,h){qa(a+"["+g+"]",h,d,e)});else e(a,b)}function da(a,b){var d={};c.each(Qa.concat.apply([],Qa.slice(0,b)),function(){d[this]=a});return d}function wa(a){if(!Na[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";Na[a]=d}return Na[a]}
function ia(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var A=O.document,c=function(){function a(){if(!b.isReady){try{A.documentElement.doScroll("left")}catch(j){setTimeout(a,1);return}b.ready()}}var b=function(j,u){return new b.fn.init(j,u)},d=O.jQuery,e=O.$,g,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,l=/\S/,n=/^\s+/,p=/\s+$/,y=/\W/,B=/\d/,K=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,L=/^[\],:{}\s]*$/,S=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,D=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
R=/(?:^|:|,)(?:\s*\[)+/g,$=/(webkit)[ \/]([\w.]+)/,f=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,o=/(mozilla)(?:.*? rv:([\w.]+))?/,q=navigator.userAgent,t=false,v=[],C,H=Object.prototype.toString,M=Object.prototype.hasOwnProperty,fa=Array.prototype.push,aa=Array.prototype.slice,ja=String.prototype.trim,ga=Array.prototype.indexOf,Y={};b.fn=b.prototype={init:function(j,u){var I,N;if(!j)return this;if(j.nodeType){this.context=this[0]=j;this.length=1;return this}if(j==="body"&&!u&&A.body){this.context=
A;this[0]=A.body;this.selector="body";this.length=1;return this}if(typeof j==="string")if((I=h.exec(j))&&(I[1]||!u))if(I[1]){N=u?u.ownerDocument||u:A;if(j=K.exec(j))if(b.isPlainObject(u)){j=[A.createElement(j[1])];b.fn.attr.call(j,u,true)}else j=[N.createElement(j[1])];else{j=b.buildFragment([I[1]],[N]);j=(j.cacheable?j.fragment.cloneNode(true):j.fragment).childNodes}return b.merge(this,j)}else{if((u=A.getElementById(I[2]))&&u.parentNode){if(u.id!==I[2])return g.find(j);this.length=1;this[0]=u}this.context=
A;this.selector=j;return this}else if(!u&&!y.test(j)){this.selector=j;this.context=A;j=A.getElementsByTagName(j);return b.merge(this,j)}else return!u||u.jquery?(u||g).find(j):b(u).find(j);else if(b.isFunction(j))return g.ready(j);if(j.selector!==G){this.selector=j.selector;this.context=j.context}return b.makeArray(j,this)},selector:"",jquery:"1.4.3",length:0,size:function(){return this.length},toArray:function(){return aa.call(this,0)},get:function(j){return j==null?this.toArray():j<0?this.slice(j)[0]:
this[j]},pushStack:function(j,u,I){var N=b();b.isArray(j)?fa.apply(N,j):b.merge(N,j);N.prevObject=this;N.context=this.context;if(u==="find")N.selector=this.selector+(this.selector?" ":"")+I;else if(u)N.selector=this.selector+"."+u+"("+I+")";return N},each:function(j,u){return b.each(this,j,u)},ready:function(j){b.bindReady();if(b.isReady)j.call(A,b);else v&&v.push(j);return this},eq:function(j){return j===-1?this.slice(j):this.slice(j,+j+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
slice:function(){return this.pushStack(aa.apply(this,arguments),"slice",aa.call(arguments).join(","))},map:function(j){return this.pushStack(b.map(this,function(u,I){return j.call(u,I,u)}))},end:function(){return this.prevObject||b(null)},push:fa,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var j=arguments[0]||{},u=1,I=arguments.length,N=false,T,U,X,W,Oa;if(typeof j==="boolean"){N=j;j=arguments[1]||{};u=2}if(typeof j!=="object"&&!b.isFunction(j))j={};if(I===
u){j=this;--u}for(;u<I;u++)if((T=arguments[u])!=null)for(U in T){X=j[U];W=T[U];if(j!==W)if(N&&W&&(b.isPlainObject(W)||(Oa=b.isArray(W)))){if(Oa){Oa=false;clone=X&&b.isArray(X)?X:[]}else clone=X&&b.isPlainObject(X)?X:{};j[U]=b.extend(N,clone,W)}else if(W!==G)j[U]=W}return j};b.extend({noConflict:function(j){O.$=e;if(j)O.jQuery=d;return b},isReady:false,readyWait:1,ready:function(j){j===true&&b.readyWait--;if(!b.readyWait||j!==true&&!b.isReady){if(!A.body)return setTimeout(b.ready,1);b.isReady=true;
if(!(j!==true&&--b.readyWait>0)){if(v){for(var u=0;j=v[u++];)j.call(A,b);v=null}b.fn.triggerHandler&&b(A).triggerHandler("ready")}}},bindReady:function(){if(!t){t=true;if(A.readyState==="complete")return setTimeout(b.ready,1);if(A.addEventListener){A.addEventListener("DOMContentLoaded",C,false);O.addEventListener("load",b.ready,false)}else if(A.attachEvent){A.attachEvent("onreadystatechange",C);O.attachEvent("onload",b.ready);var j=false;try{j=O.frameElement==null}catch(u){}A.documentElement.doScroll&&
j&&a()}}},isFunction:function(j){return b.type(j)==="function"},isArray:Array.isArray||function(j){return b.type(j)==="array"},isWindow:function(j){return j&&typeof j==="object"&&"setInterval"in j},isNaN:function(j){return j==null||!B.test(j)||isNaN(j)},type:function(j){return j==null?String(j):Y[H.call(j)]||"object"},isPlainObject:function(j){if(!j||b.type(j)!=="object"||j.nodeType||b.isWindow(j))return false;if(j.constructor&&!M.call(j,"constructor")&&!M.call(j.constructor.prototype,"isPrototypeOf"))return false;
var u;for(u in j);return u===G||M.call(j,u)},isEmptyObject:function(j){for(var u in j)return false;return true},error:function(j){throw j;},parseJSON:function(j){if(typeof j!=="string"||!j)return null;j=b.trim(j);if(L.test(j.replace(S,"@").replace(D,"]").replace(R,"")))return O.JSON&&O.JSON.parse?O.JSON.parse(j):(new Function("return "+j))();else b.error("Invalid JSON: "+j)},noop:function(){},globalEval:function(j){if(j&&l.test(j)){var u=A.getElementsByTagName("head")[0]||A.documentElement,I=A.createElement("script");
I.type="text/javascript";if(b.support.scriptEval)I.appendChild(A.createTextNode(j));else I.text=j;u.insertBefore(I,u.firstChild);u.removeChild(I)}},nodeName:function(j,u){return j.nodeName&&j.nodeName.toUpperCase()===u.toUpperCase()},each:function(j,u,I){var N,T=0,U=j.length,X=U===G||b.isFunction(j);if(I)if(X)for(N in j){if(u.apply(j[N],I)===false)break}else for(;T<U;){if(u.apply(j[T++],I)===false)break}else if(X)for(N in j){if(u.call(j[N],N,j[N])===false)break}else for(I=j[0];T<U&&u.call(I,T,I)!==
false;I=j[++T]);return j},trim:ja?function(j){return j==null?"":ja.call(j)}:function(j){return j==null?"":j.toString().replace(n,"").replace(p,"")},makeArray:function(j,u){u=u||[];if(j!=null){var I=b.type(j);j.length==null||I==="string"||I==="function"||I==="regexp"||b.isWindow(j)?fa.call(u,j):b.merge(u,j)}return u},inArray:function(j,u){if(u.indexOf)return u.indexOf(j);for(var I=0,N=u.length;I<N;I++)if(u[I]===j)return I;return-1},merge:function(j,u){var I=j.length,N=0;if(typeof u.length==="number")for(var T=
u.length;N<T;N++)j[I++]=u[N];else for(;u[N]!==G;)j[I++]=u[N++];j.length=I;return j},grep:function(j,u,I){var N=[],T;I=!!I;for(var U=0,X=j.length;U<X;U++){T=!!u(j[U],U);I!==T&&N.push(j[U])}return N},map:function(j,u,I){for(var N=[],T,U=0,X=j.length;U<X;U++){T=u(j[U],U,I);if(T!=null)N[N.length]=T}return N.concat.apply([],N)},guid:1,proxy:function(j,u,I){if(arguments.length===2)if(typeof u==="string"){I=j;j=I[u];u=G}else if(u&&!b.isFunction(u)){I=u;u=G}if(!u&&j)u=function(){return j.apply(I||this,arguments)};
if(j)u.guid=j.guid=j.guid||u.guid||b.guid++;return u},access:function(j,u,I,N,T,U){var X=j.length;if(typeof u==="object"){for(var W in u)b.access(j,W,u[W],N,T,I);return j}if(I!==G){N=!U&&N&&b.isFunction(I);for(W=0;W<X;W++)T(j[W],u,N?I.call(j[W],W,T(j[W],u)):I,U);return j}return X?T(j[0],u):G},now:function(){return(new Date).getTime()},uaMatch:function(j){j=j.toLowerCase();j=$.exec(j)||f.exec(j)||i.exec(j)||j.indexOf("compatible")<0&&o.exec(j)||[];return{browser:j[1]||"",version:j[2]||"0"}},browser:{}});
b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(j,u){Y["[object "+u+"]"]=u.toLowerCase()});q=b.uaMatch(q);if(q.browser){b.browser[q.browser]=true;b.browser.version=q.version}if(b.browser.webkit)b.browser.safari=true;if(ga)b.inArray=function(j,u){return ga.call(u,j)};if(!/\s/.test("\u00a0")){n=/^[\s\xA0]+/;p=/[\s\xA0]+$/}g=b(A);if(A.addEventListener)C=function(){A.removeEventListener("DOMContentLoaded",C,false);b.ready()};else if(A.attachEvent)C=function(){if(A.readyState===
"complete"){A.detachEvent("onreadystatechange",C);b.ready()}};return O.jQuery=O.$=b}();(function(){c.support={};var a=A.documentElement,b=A.createElement("script"),d=A.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var g=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],l=A.createElement("select"),n=l.appendChild(A.createElement("option"));if(!(!g||
!g.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:n.selected,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,
shrinkWrapBlocks:false,reliableHiddenOffsets:true};l.disabled=true;c.support.optDisabled=!n.disabled;b.type="text/javascript";try{b.appendChild(A.createTextNode("window."+e+"=1;"))}catch(p){}a.insertBefore(b,a.firstChild);if(O[e]){c.support.scriptEval=true;delete O[e]}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function y(){c.support.noCloneEvent=false;d.detachEvent("onclick",y)});d.cloneNode(true).fireEvent("onclick")}d=A.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
a=A.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var y=A.createElement("div");y.style.width=y.style.paddingLeft="1px";A.body.appendChild(y);c.boxModel=c.support.boxModel=y.offsetWidth===2;if("zoom"in y.style){y.style.display="inline";y.style.zoom=1;c.support.inlineBlockNeedsLayout=y.offsetWidth===2;y.style.display="";y.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=y.offsetWidth!==
2}y.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var B=y.getElementsByTagName("td");c.support.reliableHiddenOffsets=B[0].offsetHeight===0;B[0].style.display="";B[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&B[0].offsetHeight===0;y.innerHTML="";A.body.removeChild(y).style.display="none"});a=function(y){var B=A.createElement("div");y="on"+y;var K=y in B;if(!K){B.setAttribute(y,"return;");K=typeof B[y]==="function"}return K};
c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=g=h=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};var xa={},Ma=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=
a==O?xa:a;var e=a.nodeType,g=e?a[c.expando]:null,h=c.cache;if(!(e&&!g&&typeof b==="string"&&d===G)){if(e)g||(a[c.expando]=g=++c.uuid);else h=a;if(typeof b==="object")if(e)h[g]=c.extend(h[g],b);else c.extend(h,b);else if(e&&!h[g])h[g]={};a=e?h[g]:h;if(d!==G)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==O?xa:a;var d=a.nodeType,e=d?a[c.expando]:a,g=c.cache,h=d?g[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];
else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete g[e];else for(var l in a)delete a[l]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){if(typeof a==="undefined")return this.length?c.data(this[0]):null;else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===G){var e=this.triggerHandler("getData"+
d[1]+"!",[d[0]]);if(e===G&&this.length){e=c.data(this[0],a);if(e===G&&this[0].nodeType===1){e=this[0].getAttribute("data-"+a);if(typeof e==="string")try{e=e==="true"?true:e==="false"?false:e==="null"?null:!c.isNaN(e)?parseFloat(e):Ma.test(e)?c.parseJSON(e):e}catch(g){}else e=G}}return e===G&&d[1]?this.data(d[0]):e}else return this.each(function(){var h=c(this),l=[d[0],b];h.triggerHandler("setData"+d[1]+"!",l);c.data(this,a,b);h.triggerHandler("changeData"+d[1]+"!",l)})},removeData:function(a){return this.each(function(){c.removeData(this,
a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===G)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,
a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Ga=/[\n\t]/g,ya=/\s+/,va=/\r/g,ea=/^(?:href|src|style)$/,Ha=/^(?:button|input)$/i,Ca=/^(?:button|input|object|select|textarea)$/i,Ia=/^a(?:rea)?$/i,Ea=/^(?:radio|checkbox)$/i;
c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(y){var B=c(this);B.addClass(a.call(this,y,B.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(ya),d=0,e=this.length;d<e;d++){var g=this[d];if(g.nodeType===1)if(g.className){for(var h=" "+g.className+" ",l=g.className,n=0,p=b.length;n<
p;n++)if(h.indexOf(" "+b[n]+" ")<0)l+=" "+b[n];g.className=c.trim(l)}else g.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(p){var y=c(this);y.removeClass(a.call(this,p,y.attr("class")))});if(a&&typeof a==="string"||a===G)for(var b=(a||"").split(ya),d=0,e=this.length;d<e;d++){var g=this[d];if(g.nodeType===1&&g.className)if(a){for(var h=(" "+g.className+" ").replace(Ga," "),l=0,n=b.length;l<n;l++)h=h.replace(" "+b[l]+" "," ");g.className=c.trim(h)}else g.className=
""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(g){var h=c(this);h.toggleClass(a.call(this,g,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var g,h=0,l=c(this),n=b,p=a.split(ya);g=p[h++];){n=e?n:!l.hasClass(g);l[n?"addClass":"removeClass"](g)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,
"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ga," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var g=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:g.length;h<e;h++){var l=g[h];if(l.selected&&
(c.support.optDisabled?!l.disabled:l.getAttribute("disabled")===null)&&(!l.parentNode.disabled||!c.nodeName(l.parentNode,"optgroup"))){a=c(l).val();if(b)return a;d.push(a)}}return d}if(Ea.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(va,"")}return G}var n=c.isFunction(a);return this.each(function(p){var y=c(this),B=a;if(this.nodeType===1){if(n)B=a.call(this,p,y.val());if(B==null)B="";else if(typeof B==="number")B+="";else if(c.isArray(B))B=
c.map(B,function(L){return L==null?"":L+""});if(c.isArray(B)&&Ea.test(this.type))this.checked=c.inArray(y.val(),B)>=0;else if(c.nodeName(this,"select")){var K=c.makeArray(B);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),K)>=0});if(!K.length)this.selectedIndex=-1}else this.value=B}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return G;if(e&&b in c.attrFn)return c(a)[b](d);
e=a.nodeType!==1||!c.isXMLDoc(a);var g=d!==G;b=e&&c.props[b]||b;if(a.nodeType===1){var h=ea.test(b);if((b in a||a[b]!==G)&&e&&!h){if(g){b==="type"&&Ha.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:Ca.test(a.nodeName)||Ia.test(a.nodeName)&&a.href?
0:G;return a[b]}if(!c.support.style&&e&&b==="style"){if(g)a.style.cssText=""+d;return a.style.cssText}g&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return G;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?G:a}}});var na=/\.(.*)$/,x=/^(?:textarea|input|select)$/i,ta=/\./g,pa=/ /g,Ja=/[^\w\s.|`]/g,za=function(a){return a.replace(Ja,"\\$&")},k={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===
8)){if(c.isWindow(a)&&a!==O&&!a.frameElement)a=O;if(d===false)d=ka;var g,h;if(d.handler){g=d;d=g.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var l=a.nodeType?"events":"__events__",n=h[l],p=h.handle;if(typeof n==="function"){p=n.handle;n=n.events}else if(!n){a.nodeType||(h[l]=h=function(){});h.events=n={}}if(!p)h.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):G};p.elem=a;b=b.split(" ");for(var y=0,B;l=b[y++];){h=g?c.extend({},g):
{handler:d,data:e};if(l.indexOf(".")>-1){B=l.split(".");l=B.shift();h.namespace=B.slice(0).sort().join(".")}else{B=[];h.namespace=""}h.type=l;if(!h.guid)h.guid=d.guid;var K=n[l],L=c.event.special[l]||{};if(!K){K=n[l]=[];if(!L.setup||L.setup.call(a,e,B,p)===false)if(a.addEventListener)a.addEventListener(l,p,false);else a.attachEvent&&a.attachEvent("on"+l,p)}if(L.add){L.add.call(a,h);if(!h.handler.guid)h.handler.guid=d.guid}K.push(h);c.event.global[l]=true}a=null}}},global:{},remove:function(a,b,d,
e){if(!(a.nodeType===3||a.nodeType===8)){if(d===false)d=ka;var g,h,l=0,n,p,y,B,K,L,S=a.nodeType?"events":"__events__",D=c.data(a),R=D&&D[S];if(D&&R){if(typeof R==="function"){D=R;R=R.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(g in R)c.event.remove(a,g+b)}else{for(b=b.split(" ");g=b[l++];){B=g;n=g.indexOf(".")<0;p=[];if(!n){p=g.split(".");g=p.shift();y=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),za).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(K=R[g])if(d){B=
c.event.special[g]||{};for(h=e||0;h<K.length;h++){L=K[h];if(d.guid===L.guid){if(n||y.test(L.namespace)){e==null&&K.splice(h--,1);B.remove&&B.remove.call(a,L)}if(e!=null)break}}if(K.length===0||e!=null&&K.length===1){if(!B.teardown||B.teardown.call(a,p)===false)c.removeEvent(a,g,D.handle);delete R[g]}}else for(h=0;h<K.length;h++){L=K[h];if(n||y.test(L.namespace)){c.event.remove(a,B,L.handler,h);K.splice(h--,1)}}}if(c.isEmptyObject(R)){if(b=D.handle)b.elem=null;delete D.events;delete D.handle;if(typeof D===
"function")c.removeData(a,S);else c.isEmptyObject(D)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var g=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(g),a):c.Event(g);if(g.indexOf("!")>=0){a.type=g=g.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[g]&&c.each(c.cache,function(){this.events&&this.events[g]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return G;a.result=G;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=
d;(e=d.nodeType?c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+g]&&d["on"+g].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){e=a.target;var l,n=g.replace(na,""),p=c.nodeName(e,"a")&&n==="click",y=c.event.special[n]||{};if((!y._default||y._default.call(d,a)===false)&&
!p&&!(e&&e.nodeName&&c.noData[e.nodeName.toLowerCase()])){try{if(e[n]){if(l=e["on"+n])e["on"+n]=null;c.event.triggered=true;e[n]()}}catch(B){}if(l)e["on"+n]=l;c.event.triggered=false}}},handle:function(a){var b,d,e;d=[];var g,h=c.makeArray(arguments);a=h[0]=c.event.fix(a||O.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");g=
c.data(this,this.nodeType?"events":"__events__");if(typeof g==="function")g=g.events;d=(g||{})[a.type];if(g&&d){d=d.slice(0);g=0;for(var l=d.length;g<l;g++){var n=d[g];if(b||e.test(n.namespace)){a.handler=n.handler;a.data=n.data;a.handleObj=n;n=n.handler.apply(this,h);if(n!==G){a.result=n;if(n===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||A;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=A.documentElement;d=A.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==G)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,sa(a.origType,a.selector),c.extend({},a,{handler:Da,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
sa(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=A.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=
c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=ra;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=ra;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=ra;this.stopPropagation()},isDefaultPrevented:ka,isPropagationStopped:ka,isImmediatePropagationStopped:ka};
var m=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},s=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?s:m,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?s:m)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=G;return oa("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=G;return oa("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var r,
w=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},z=function(a,b){var d=a.target,e,g;if(!(!x.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");g=w(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",g);if(!(e===G||g===e))if(e!=null||g){a.type="change";a.liveFired=
G;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:z,beforedeactivate:z,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return z.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return z.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",w(a))}},setup:function(){if(this.type===
"file")return false;for(var a in r)c.event.add(this,a+".specialChange",r[a]);return x.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return x.test(this.nodeName)}};r=c.event.special.change.filters;r.focus=r.beforeactivate}A.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){k[b]++===0&&A.addEventListener(a,d,true)},teardown:function(){--k[b]===
0&&A.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,g){if(typeof d==="object"){for(var h in d)this[b](h,e,d[h],g);return this}if(c.isFunction(e)||e===false){g=e;e=G}var l=b==="one"?c.proxy(g,function(p){c(this).unbind(p,l);return g.apply(this,arguments)}):g;if(d==="unload"&&b!=="one")this.one(d,e,g);else{h=0;for(var n=this.length;h<n;h++)c.event.add(this[h],d,l,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<
b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var g=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,g+1);e.preventDefault();return b[g].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var F={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,g,h){var l,n=0,p,y,B=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&
!d.preventDefault){for(l in d)h[b](l,e,d[l],B);return this}if(c.isFunction(e)){g=e;e=G}for(d=(d||"").split(" ");(l=d[n++])!=null;){p=na.exec(l);y="";if(p){y=p[0];l=l.replace(na,"")}if(l==="hover")d.push("mouseenter"+y,"mouseleave"+y);else{p=l;if(l==="focus"||l==="blur"){d.push(F[l]+y);l+=y}else l=(F[l]||l)+y;if(b==="live"){y=0;for(var K=h.length;y<K;y++)c.event.add(h[y],"live."+sa(l,B),{data:e,selector:B,handler:g,origType:l,origHandler:g,preType:p})}else h.unbind("live."+sa(l,B),g)}}return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});O.attachEvent&&!O.addEventListener&&c(O).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(f,i,o,q,t,v){t=0;for(var C=q.length;t<C;t++){var H=q[t];if(H){H=H[f];for(var M=false;H;){if(H.sizcache===o){M=q[H.sizset];break}if(H.nodeType===1&&!v){H.sizcache=o;H.sizset=t}if(H.nodeName.toLowerCase()===i){M=H;break}H=H[f]}q[t]=M}}}function b(f,i,o,q,t,v){t=0;for(var C=q.length;t<C;t++){var H=q[t];if(H){H=H[f];for(var M=false;H;){if(H.sizcache===o){M=q[H.sizset];break}if(H.nodeType===1){if(!v){H.sizcache=o;H.sizset=t}if(typeof i!=="string"){if(H===i){M=true;break}}else if(n.filter(i,
[H]).length>0){M=H;break}}H=H[f]}q[t]=M}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,g=Object.prototype.toString,h=false,l=true;[0,0].sort(function(){l=false;return 0});var n=function(f,i,o,q){o=o||[];var t=i=i||A;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!f||typeof f!=="string")return o;var v=[],C,H,M,fa,aa=true,ja=n.isXML(i),ga=f,Y;do{d.exec("");if(C=d.exec(ga)){ga=C[3];v.push(C[1]);if(C[2]){fa=
C[3];break}}}while(C);if(v.length>1&&y.exec(f))if(v.length===2&&p.relative[v[0]])H=$(v[0]+v[1],i);else for(H=p.relative[v[0]]?[i]:n(v.shift(),i);v.length;){f=v.shift();if(p.relative[f])f+=v.shift();H=$(f,H)}else{if(!q&&v.length>1&&i.nodeType===9&&!ja&&p.match.ID.test(v[0])&&!p.match.ID.test(v[v.length-1])){C=n.find(v.shift(),i,ja);i=C.expr?n.filter(C.expr,C.set)[0]:C.set[0]}if(i){C=q?{expr:v.pop(),set:L(q)}:n.find(v.pop(),v.length===1&&(v[0]==="~"||v[0]==="+")&&i.parentNode?i.parentNode:i,ja);H=C.expr?
n.filter(C.expr,C.set):C.set;if(v.length>0)M=L(H);else aa=false;for(;v.length;){C=Y=v.pop();if(p.relative[Y])C=v.pop();else Y="";if(C==null)C=i;p.relative[Y](M,C,ja)}}else M=[]}M||(M=H);M||n.error(Y||f);if(g.call(M)==="[object Array]")if(aa)if(i&&i.nodeType===1)for(f=0;M[f]!=null;f++){if(M[f]&&(M[f]===true||M[f].nodeType===1&&n.contains(i,M[f])))o.push(H[f])}else for(f=0;M[f]!=null;f++)M[f]&&M[f].nodeType===1&&o.push(H[f]);else o.push.apply(o,M);else L(M,o);if(fa){n(fa,t,o,q);n.uniqueSort(o)}return o};
n.uniqueSort=function(f){if(D){h=l;f.sort(D);if(h)for(var i=1;i<f.length;i++)f[i]===f[i-1]&&f.splice(i--,1)}return f};n.matches=function(f,i){return n(f,null,null,i)};n.matchesSelector=function(f,i){return n(i,null,null,[f]).length>0};n.find=function(f,i,o){var q;if(!f)return[];for(var t=0,v=p.order.length;t<v;t++){var C=p.order[t],H;if(H=p.leftMatch[C].exec(f)){var M=H[1];H.splice(1,1);if(M.substr(M.length-1)!=="\\"){H[1]=(H[1]||"").replace(/\\/g,"");q=p.find[C](H,i,o);if(q!=null){f=f.replace(p.match[C],
"");break}}}}q||(q=i.getElementsByTagName("*"));return{set:q,expr:f}};n.filter=function(f,i,o,q){for(var t=f,v=[],C=i,H,M,fa=i&&i[0]&&n.isXML(i[0]);f&&i.length;){for(var aa in p.filter)if((H=p.leftMatch[aa].exec(f))!=null&&H[2]){var ja=p.filter[aa],ga,Y;Y=H[1];M=false;H.splice(1,1);if(Y.substr(Y.length-1)!=="\\"){if(C===v)v=[];if(p.preFilter[aa])if(H=p.preFilter[aa](H,C,o,v,q,fa)){if(H===true)continue}else M=ga=true;if(H)for(var j=0;(Y=C[j])!=null;j++)if(Y){ga=ja(Y,H,j,C);var u=q^!!ga;if(o&&ga!=null)if(u)M=
true;else C[j]=false;else if(u){v.push(Y);M=true}}if(ga!==G){o||(C=v);f=f.replace(p.match[aa],"");if(!M)return[];break}}}if(f===t)if(M==null)n.error(f);else break;t=f}return C};n.error=function(f){throw"Syntax error, unrecognized expression: "+f;};var p=n.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(f){return f.getAttribute("href")}},relative:{"+":function(f,i){var o=typeof i==="string",q=o&&!/\W/.test(i);o=o&&!q;if(q)i=i.toLowerCase();q=0;for(var t=f.length,
v;q<t;q++)if(v=f[q]){for(;(v=v.previousSibling)&&v.nodeType!==1;);f[q]=o||v&&v.nodeName.toLowerCase()===i?v||false:v===i}o&&n.filter(i,f,true)},">":function(f,i){var o=typeof i==="string",q,t=0,v=f.length;if(o&&!/\W/.test(i))for(i=i.toLowerCase();t<v;t++){if(q=f[t]){o=q.parentNode;f[t]=o.nodeName.toLowerCase()===i?o:false}}else{for(;t<v;t++)if(q=f[t])f[t]=o?q.parentNode:q.parentNode===i;o&&n.filter(i,f,true)}},"":function(f,i,o){var q=e++,t=b,v;if(typeof i==="string"&&!/\W/.test(i)){v=i=i.toLowerCase();
t=a}t("parentNode",i,q,f,v,o)},"~":function(f,i,o){var q=e++,t=b,v;if(typeof i==="string"&&!/\W/.test(i)){v=i=i.toLowerCase();t=a}t("previousSibling",i,q,f,v,o)}},find:{ID:function(f,i,o){if(typeof i.getElementById!=="undefined"&&!o)return(f=i.getElementById(f[1]))&&f.parentNode?[f]:[]},NAME:function(f,i){if(typeof i.getElementsByName!=="undefined"){var o=[];i=i.getElementsByName(f[1]);for(var q=0,t=i.length;q<t;q++)i[q].getAttribute("name")===f[1]&&o.push(i[q]);return o.length===0?null:o}},TAG:function(f,
i){return i.getElementsByTagName(f[1])}},preFilter:{CLASS:function(f,i,o,q,t,v){f=" "+f[1].replace(/\\/g,"")+" ";if(v)return f;v=0;for(var C;(C=i[v])!=null;v++)if(C)if(t^(C.className&&(" "+C.className+" ").replace(/[\t\n]/g," ").indexOf(f)>=0))o||q.push(C);else if(o)i[v]=false;return false},ID:function(f){return f[1].replace(/\\/g,"")},TAG:function(f){return f[1].toLowerCase()},CHILD:function(f){if(f[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(f[2]==="even"&&"2n"||f[2]==="odd"&&"2n+1"||!/\D/.test(f[2])&&
"0n+"+f[2]||f[2]);f[2]=i[1]+(i[2]||1)-0;f[3]=i[3]-0}f[0]=e++;return f},ATTR:function(f,i,o,q,t,v){i=f[1].replace(/\\/g,"");if(!v&&p.attrMap[i])f[1]=p.attrMap[i];if(f[2]==="~=")f[4]=" "+f[4]+" ";return f},PSEUDO:function(f,i,o,q,t){if(f[1]==="not")if((d.exec(f[3])||"").length>1||/^\w/.test(f[3]))f[3]=n(f[3],null,null,i);else{f=n.filter(f[3],i,o,true^t);o||q.push.apply(q,f);return false}else if(p.match.POS.test(f[0])||p.match.CHILD.test(f[0]))return true;return f},POS:function(f){f.unshift(true);return f}},
filters:{enabled:function(f){return f.disabled===false&&f.type!=="hidden"},disabled:function(f){return f.disabled===true},checked:function(f){return f.checked===true},selected:function(f){return f.selected===true},parent:function(f){return!!f.firstChild},empty:function(f){return!f.firstChild},has:function(f,i,o){return!!n(o[3],f).length},header:function(f){return/h\d/i.test(f.nodeName)},text:function(f){return"text"===f.type},radio:function(f){return"radio"===f.type},checkbox:function(f){return"checkbox"===
f.type},file:function(f){return"file"===f.type},password:function(f){return"password"===f.type},submit:function(f){return"submit"===f.type},image:function(f){return"image"===f.type},reset:function(f){return"reset"===f.type},button:function(f){return"button"===f.type||f.nodeName.toLowerCase()==="button"},input:function(f){return/input|select|textarea|button/i.test(f.nodeName)}},setFilters:{first:function(f,i){return i===0},last:function(f,i,o,q){return i===q.length-1},even:function(f,i){return i%2===
0},odd:function(f,i){return i%2===1},lt:function(f,i,o){return i<o[3]-0},gt:function(f,i,o){return i>o[3]-0},nth:function(f,i,o){return o[3]-0===i},eq:function(f,i,o){return o[3]-0===i}},filter:{PSEUDO:function(f,i,o,q){var t=i[1],v=p.filters[t];if(v)return v(f,o,i,q);else if(t==="contains")return(f.textContent||f.innerText||n.getText([f])||"").indexOf(i[3])>=0;else if(t==="not"){i=i[3];o=0;for(q=i.length;o<q;o++)if(i[o]===f)return false;return true}else n.error("Syntax error, unrecognized expression: "+
t)},CHILD:function(f,i){var o=i[1],q=f;switch(o){case "only":case "first":for(;q=q.previousSibling;)if(q.nodeType===1)return false;if(o==="first")return true;q=f;case "last":for(;q=q.nextSibling;)if(q.nodeType===1)return false;return true;case "nth":o=i[2];var t=i[3];if(o===1&&t===0)return true;i=i[0];var v=f.parentNode;if(v&&(v.sizcache!==i||!f.nodeIndex)){var C=0;for(q=v.firstChild;q;q=q.nextSibling)if(q.nodeType===1)q.nodeIndex=++C;v.sizcache=i}f=f.nodeIndex-t;return o===0?f===0:f%o===0&&f/o>=
0}},ID:function(f,i){return f.nodeType===1&&f.getAttribute("id")===i},TAG:function(f,i){return i==="*"&&f.nodeType===1||f.nodeName.toLowerCase()===i},CLASS:function(f,i){return(" "+(f.className||f.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(f,i){var o=i[1];f=p.attrHandle[o]?p.attrHandle[o](f):f[o]!=null?f[o]:f.getAttribute(o);o=f+"";var q=i[2];i=i[4];return f==null?q==="!=":q==="="?o===i:q==="*="?o.indexOf(i)>=0:q==="~="?(" "+o+" ").indexOf(i)>=0:!i?o&&f!==false:q==="!="?o!==i:q==="^="?
o.indexOf(i)===0:q==="$="?o.substr(o.length-i.length)===i:q==="|="?o===i||o.substr(0,i.length+1)===i+"-":false},POS:function(f,i,o,q){var t=p.setFilters[i[2]];if(t)return t(f,o,i,q)}}},y=p.match.POS,B=function(f,i){return"\\"+(i-0+1)};for(var K in p.match){p.match[K]=new RegExp(p.match[K].source+/(?![^\[]*\])(?![^\(]*\))/.source);p.leftMatch[K]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[K].source.replace(/\\(\d+)/g,B))}var L=function(f,i){f=Array.prototype.slice.call(f,0);if(i){i.push.apply(i,f);
return i}return f};try{Array.prototype.slice.call(A.documentElement.childNodes,0)}catch(S){L=function(f,i){i=i||[];var o=0;if(g.call(f)==="[object Array]")Array.prototype.push.apply(i,f);else if(typeof f.length==="number")for(var q=f.length;o<q;o++)i.push(f[o]);else for(;f[o];o++)i.push(f[o]);return i}}var D,R;if(A.documentElement.compareDocumentPosition)D=function(f,i){if(f===i){h=true;return 0}if(!f.compareDocumentPosition||!i.compareDocumentPosition)return f.compareDocumentPosition?-1:1;return f.compareDocumentPosition(i)&
4?-1:1};else{D=function(f,i){var o=[],q=[],t=f.parentNode,v=i.parentNode,C=t;if(f===i){h=true;return 0}else if(t===v)return R(f,i);else if(t){if(!v)return 1}else return-1;for(;C;){o.unshift(C);C=C.parentNode}for(C=v;C;){q.unshift(C);C=C.parentNode}t=o.length;v=q.length;for(C=0;C<t&&C<v;C++)if(o[C]!==q[C])return R(o[C],q[C]);return C===t?R(f,q[C],-1):R(o[C],i,1)};R=function(f,i,o){if(f===i)return o;for(f=f.nextSibling;f;){if(f===i)return-1;f=f.nextSibling}return 1}}n.getText=function(f){for(var i=
"",o,q=0;f[q];q++){o=f[q];if(o.nodeType===3||o.nodeType===4)i+=o.nodeValue;else if(o.nodeType!==8)i+=n.getText(o.childNodes)}return i};(function(){var f=A.createElement("div"),i="script"+(new Date).getTime();f.innerHTML="<a name='"+i+"'/>";var o=A.documentElement;o.insertBefore(f,o.firstChild);if(A.getElementById(i)){p.find.ID=function(q,t,v){if(typeof t.getElementById!=="undefined"&&!v)return(t=t.getElementById(q[1]))?t.id===q[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===
q[1]?[t]:G:[]};p.filter.ID=function(q,t){var v=typeof q.getAttributeNode!=="undefined"&&q.getAttributeNode("id");return q.nodeType===1&&v&&v.nodeValue===t}}o.removeChild(f);o=f=null})();(function(){var f=A.createElement("div");f.appendChild(A.createComment(""));if(f.getElementsByTagName("*").length>0)p.find.TAG=function(i,o){o=o.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var q=0;o[q];q++)o[q].nodeType===1&&i.push(o[q]);o=i}return o};f.innerHTML="<a href='#'></a>";if(f.firstChild&&typeof f.firstChild.getAttribute!==
"undefined"&&f.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(i){return i.getAttribute("href",2)};f=null})();A.querySelectorAll&&function(){var f=n,i=A.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){n=function(q,t,v,C){t=t||A;if(!C&&!n.isXML(t))if(t.nodeType===9)try{return L(t.querySelectorAll(q),v)}catch(H){}else if(t.nodeType===1&&t.nodeName.toLowerCase()!=="object"){var M=t.id,fa=t.id="__sizzle__";try{return L(t.querySelectorAll("#"+
fa+" "+q),v)}catch(aa){}finally{if(M)t.id=M;else t.removeAttribute("id")}}return f(q,t,v,C)};for(var o in f)n[o]=f[o];i=null}}();(function(){var f=A.documentElement,i=f.matchesSelector||f.mozMatchesSelector||f.webkitMatchesSelector||f.msMatchesSelector,o=false;try{i.call(A.documentElement,":sizzle")}catch(q){o=true}if(i)n.matchesSelector=function(t,v){try{if(o||!p.match.PSEUDO.test(v))return i.call(t,v)}catch(C){}return n(v,null,null,[t]).length>0}})();(function(){var f=A.createElement("div");f.innerHTML=
"<div class='test e'></div><div class='test'></div>";if(!(!f.getElementsByClassName||f.getElementsByClassName("e").length===0)){f.lastChild.className="e";if(f.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(i,o,q){if(typeof o.getElementsByClassName!=="undefined"&&!q)return o.getElementsByClassName(i[1])};f=null}}})();n.contains=A.documentElement.contains?function(f,i){return f!==i&&(f.contains?f.contains(i):true)}:function(f,i){return!!(f.compareDocumentPosition(i)&
16)};n.isXML=function(f){return(f=(f?f.ownerDocument||f:0).documentElement)?f.nodeName!=="HTML":false};var $=function(f,i){var o=[],q="",t;for(i=i.nodeType?[i]:i;t=p.match.PSEUDO.exec(f);){q+=t[0];f=f.replace(p.match.PSEUDO,"")}f=p.relative[f]?f+"*":f;t=0;for(var v=i.length;t<v;t++)n(f,i[t],o);return n.filter(q,o)};c.find=n;c.expr=n.selectors;c.expr[":"]=c.expr.filters;c.unique=n.uniqueSort;c.text=n.getText;c.isXMLDoc=n.isXML;c.contains=n.contains})();var J=/Until$/,Q=/^(?:parents|prevUntil|prevAll)/,
P=/,/,V=/^.[^:#\[\.,]*$/,ha=Array.prototype.slice,Aa=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("","find",a),d=0,e=0,g=this.length;e<g;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<b.length;h++)for(var l=0;l<d;l++)if(b[l]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Fa(this,a,false),"not",a)},filter:function(a){return this.pushStack(Fa(this,
a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){var d=[],e,g,h=this[0];if(c.isArray(a)){var l={},n,p=1;if(h&&a.length){e=0;for(g=a.length;e<g;e++){n=a[e];l[n]||(l[n]=c.expr.match.POS.test(n)?c(n,b||this.context):n)}for(;h&&h.ownerDocument&&h!==b;){for(n in l){a=l[n];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:n,elem:h,level:p})}h=h.parentNode;p++}}return d}l=Aa.test(a)?c(a,b||this.context):null;e=0;for(g=this.length;e<g;e++)for(h=this[e];h;)if(l?
l.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(la(a[0])||la(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});
c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",
d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var g=c.map(this,b,d);J.test(a)||(e=d);if(e&&typeof e==="string")g=c.filter(e,g);g=this.length>1?c.unique(g):g;if((this.length>1||P.test(e))&&Q.test(a))g=g.reverse();return this.pushStack(g,a,ha.call(arguments).join(","))}});
c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&a.nodeType!==9&&(d===G||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Ra=/ jQuery\d+="(?:\d+|null)"/g,
Ka=/^\s+/,Sa=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Ta=/<([\w:]+)/,cb=/<tbody/i,db=/<|&#?\w+;/,Ua=/<(?:script|object|embed|option|style)/i,Va=/checked\s*(?:[^=]|=\s*.checked.)/i,eb=/\=([^="'>\s]+\/)>/g,ba={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>",
"</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};ba.optgroup=ba.option;ba.tbody=ba.tfoot=ba.colgroup=ba.caption=ba.thead;ba.th=ba.td;if(!c.support.htmlSerialize)ba._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==G)return this.empty().append((this[0]&&this[0].ownerDocument||A).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,
d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},
unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=
c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));
c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Ra,"").replace(eb,'="$1">').replace(Ka,
"")],e)[0]}else return this.cloneNode(true)});if(a===true){E(this,b);E(this.find("*"),b.find("*"))}return b},html:function(a){if(a===G)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Ra,""):null;else if(typeof a==="string"&&!Ua.test(a)&&(c.support.leadingWhitespace||!Ka.test(a))&&!ba[(Ta.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Sa,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?
this.each(function(g){var h=c(this);h.html(a.call(this,g,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,
true)},domManip:function(a,b,d){var e,g,h=a[0],l=[],n;if(!c.support.checkClone&&arguments.length===3&&typeof h==="string"&&Va.test(h))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(h))return this.each(function(B){var K=c(this);a[0]=h.call(this,B,b?K.html():G);K.domManip(a,b,d)});if(this[0]){e=h&&h.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,l);n=e.fragment;if(g=n.childNodes.length===1?(n=n.firstChild):
n.firstChild){b=b&&c.nodeName(g,"tr");for(var p=0,y=this.length;p<y;p++)d.call(b?ca(this[p],g):this[p],p>0||e.cacheable||this.length>1?n.cloneNode(true):n)}l.length&&c.each(l,Z)}return this}});c.buildFragment=function(a,b,d){var e,g,h;b=b&&b[0]?b[0].ownerDocument||b[0]:A;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===A&&!Ua.test(a[0])&&(c.support.checkClone||!Va.test(a[0]))){g=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(g)c.fragments[a[0]]=
h?e:1;return{fragment:e,cacheable:g}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var g=this.length===1&&this[0].parentNode;if(g&&g.nodeType===11&&g.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{g=0;for(var h=d.length;g<h;g++){var l=(g>0?this.clone(true):this).get();c(d[g])[b](l);e=e.concat(l)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,
b,d,e){b=b||A;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||A;for(var g=[],h=0,l;(l=a[h])!=null;h++){if(typeof l==="number")l+="";if(l){if(typeof l==="string"&&!db.test(l))l=b.createTextNode(l);else if(typeof l==="string"){l=l.replace(Sa,"<$1></$2>");var n=(Ta.exec(l)||["",""])[1].toLowerCase(),p=ba[n]||ba._default,y=p[0],B=b.createElement("div");for(B.innerHTML=p[1]+l+p[2];y--;)B=B.lastChild;if(!c.support.tbody){y=cb.test(l);n=n==="table"&&!y?B.firstChild&&
B.firstChild.childNodes:p[1]==="<table>"&&!y?B.childNodes:[];for(p=n.length-1;p>=0;--p)c.nodeName(n[p],"tbody")&&!n[p].childNodes.length&&n[p].parentNode.removeChild(n[p])}!c.support.leadingWhitespace&&Ka.test(l)&&B.insertBefore(b.createTextNode(Ka.exec(l)[0]),B.firstChild);l=B.childNodes}if(l.nodeType)g.push(l);else g=c.merge(g,l)}}if(d)for(h=0;g[h];h++)if(e&&c.nodeName(g[h],"script")&&(!g[h].type||g[h].type.toLowerCase()==="text/javascript"))e.push(g[h].parentNode?g[h].parentNode.removeChild(g[h]):
g[h]);else{g[h].nodeType===1&&g.splice.apply(g,[h+1,0].concat(c.makeArray(g[h].getElementsByTagName("script"))));d.appendChild(g[h])}return g},cleanData:function(a){for(var b,d,e=c.cache,g=c.event.special,h=c.support.deleteExpando,l=0,n;(n=a[l])!=null;l++)if(!(n.nodeName&&c.noData[n.nodeName.toLowerCase()]))if(d=n[c.expando]){if((b=e[d])&&b.events)for(var p in b.events)g[p]?c.event.remove(n,p):c.removeEvent(n,p,b.handle);if(h)delete n[c.expando];else n.removeAttribute&&n.removeAttribute(c.expando);
delete e[d]}}});var Wa=/alpha\([^)]*\)/i,fb=/opacity=([^)]*)/,gb=/-([a-z])/ig,hb=/([A-Z])/g,Xa=/^-?\d+(?:px)?$/i,ib=/^-?\d/,jb={position:"absolute",visibility:"hidden",display:"block"},$a=["Left","Right"],ab=["Top","Bottom"],Ba,kb=A.defaultView&&A.defaultView.getComputedStyle,lb=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===G)return this;return c.access(this,a,b,true,function(d,e,g){return g!==G?c.style(d,e,g):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,
b){if(b){a=Ba(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var g,h=c.camelCase(b),l=a.style,n=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==G){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!n||!("set"in n)||(d=
n.set(a,d))!==G)try{l[b]=d}catch(p){}}}else{if(n&&"get"in n&&(g=n.get(a,false,e))!==G)return g;return l[b]}}},css:function(a,b,d){var e,g=c.camelCase(b),h=c.cssHooks[g];b=c.cssProps[g]||g;if(h&&"get"in h&&(e=h.get(a,true,d))!==G)return e;else if(Ba)return Ba(a,b,g)},swap:function(a,b,d){var e={};for(var g in b){e[g]=a.style[g];a.style[g]=b[g]}d.call(a);for(g in b)a.style[g]=e[g]},camelCase:function(a){return a.replace(gb,lb)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]=
{get:function(d,e,g){var h;if(e){if(d.offsetWidth!==0)h=ma(d,b,g);else c.swap(d,jb,function(){h=ma(d,b,g)});return h+"px"}},set:function(d,e){if(Xa.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return fb.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=Wa.test(d)?
d.replace(Wa,b):a.filter+" "+b}};if(kb)Ba=function(a,b,d){var e;d=d.replace(hb,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return G;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};else if(A.documentElement.currentStyle)Ba=function(a,b){var d,e,g=a.currentStyle&&a.currentStyle[b],h=a.style;if(!Xa.test(g)&&ib.test(g)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=
b==="fontSize"?"1em":g||0;g=h.pixelLeft+"px";h.left=d;a.runtimeStyle.left=e}return g};if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var mb=c.now(),nb=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,ob=/^(?:select|textarea)/i,pb=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
qb=/^(?:GET|HEAD|DELETE)$/,bb=/\[\]$/,ua=/\=\?(&|$)/,Pa=/\?/,rb=/([?&])_=[^&]*/,sb=/^(\w+:)?\/\/([^\/?#]+)/,tb=/%20/g,ub=/#.*$/,Ya=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&Ya)return Ya.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var g=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",
data:b,complete:function(l,n){if(n==="success"||n==="notmodified")h.html(g?c("<div>").append(l.responseText.replace(nb,"")).find(g):l.responseText);d&&h.each(d,[l.responseText,n,l])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||ob.test(this.nodeName)||pb.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new O.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,g,h=b.type.toUpperCase(),l=qb.test(h);b.url=b.url.replace(ub,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")ua.test(b.url)||(b.url+=(Pa.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!ua.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&
(b.data&&ua.test(b.data)||ua.test(b.url))){d=b.jsonpCallback||"jsonp"+mb++;if(b.data)b.data=(b.data+"").replace(ua,"="+d+"$1");b.url=b.url.replace(ua,"="+d+"$1");b.dataType="script";var n=O[d];O[d]=function(q){g=q;c.handleSuccess(b,D,e,g);c.handleComplete(b,D,e,g);if(c.isFunction(n))n(q);else{O[d]=G;try{delete O[d]}catch(t){}}B&&B.removeChild(K)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&h==="GET"){var p=c.now(),y=b.url.replace(rb,"$1_="+p);b.url=y+(y===b.url?(Pa.test(b.url)?
"&":"?")+"_="+p:"")}if(b.data&&h==="GET")b.url+=(Pa.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");p=(p=sb.exec(b.url))&&(p[1]&&p[1]!==location.protocol||p[2]!==location.host);if(b.dataType==="script"&&h==="GET"&&p){var B=A.getElementsByTagName("head")[0]||A.documentElement,K=A.createElement("script");if(b.scriptCharset)K.charset=b.scriptCharset;K.src=b.url;if(!d){var L=false;K.onload=K.onreadystatechange=function(){if(!L&&(!this.readyState||this.readyState==="loaded"||
this.readyState==="complete")){L=true;c.handleSuccess(b,D,e,g);c.handleComplete(b,D,e,g);K.onload=K.onreadystatechange=null;B&&K.parentNode&&B.removeChild(K)}}}B.insertBefore(K,B.firstChild);return G}var S=false,D=b.xhr();if(D){b.username?D.open(h,b.url,b.async,b.username,b.password):D.open(h,b.url,b.async);try{if(b.data!=null&&!l||a&&a.contentType)D.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&D.setRequestHeader("If-Modified-Since",c.lastModified[b.url]);
c.etag[b.url]&&D.setRequestHeader("If-None-Match",c.etag[b.url])}p||D.setRequestHeader("X-Requested-With","XMLHttpRequest");D.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(R){}if(b.beforeSend&&b.beforeSend.call(b.context,D,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");D.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[D,b]);var $=D.onreadystatechange=function(q){if(!D||D.readyState===0||q===
"abort"){S||c.handleComplete(b,D,e,g);S=true;if(D)D.onreadystatechange=c.noop}else if(!S&&D&&(D.readyState===4||q==="timeout")){S=true;D.onreadystatechange=c.noop;e=q==="timeout"?"timeout":!c.httpSuccess(D)?"error":b.ifModified&&c.httpNotModified(D,b.url)?"notmodified":"success";var t;if(e==="success")try{g=c.httpData(D,b.dataType,b)}catch(v){e="parsererror";t=v}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,D,e,g);else c.handleError(b,D,e,t);d||c.handleComplete(b,D,e,g);q==="timeout"&&
D.abort();if(b.async)D=null}};try{var f=D.abort;D.abort=function(){D&&f.call&&f.call(D);$("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){D&&!S&&$("timeout")},b.timeout);try{D.send(l||b.data==null?null:b.data)}catch(o){c.handleError(b,D,null,o);c.handleComplete(b,D,e,g)}b.async||$();return D}},param:function(a,b){var d=[],e=function(h,l){l=c.isFunction(l)?l():l;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(l)};if(b===G)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery)c.each(a,
function(){e(this.name,this.value)});else for(var g in a)qa(g,a[g],b,e);return d.join("&").replace(tb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,d);a.global&&c.triggerGlobal(a,"ajaxComplete",
[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=e;return a.status===304},httpData:function(a,
b,d){var e=a.getResponseHeader("content-type")||"",g=b==="xml"||!b&&e.indexOf("xml")>=0;a=g?a.responseXML:a.responseText;g&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(O.ActiveXObject)c.ajaxSettings.xhr=function(){if(O.location.protocol!=="file:")try{return new O.XMLHttpRequest}catch(a){}try{return new O.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};
c.support.ajax=!!c.ajaxSettings.xhr();var Na={},vb=/^(?:toggle|show|hide)$/,wb=/^([+\-]=)?([\d+.\-]+)(.*)$/,La,Qa=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(da("show",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){if(!c.data(this[a],"olddisplay")&&this[a].style.display==="none")this[a].style.display="";this[a].style.display===""&&
c.css(this[a],"display")==="none"&&c.data(this[a],"olddisplay",wa(this[a].nodeName))}for(a=0;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b,d){if(a||a===0)return this.animate(da("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,
arguments);else a==null||e?this.each(function(){var g=e?a:c(this).is(":hidden");c(this)[g?"show":"hide"]()}):this.animate(da("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var g=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(g.complete);return this[g.queue===false?"each":"queue"](function(){var h=c.extend({},g),l,n=this.nodeType===1,p=n&&c(this).is(":hidden"),y=this;for(l in a){var B=
c.camelCase(l);if(l!==B){a[B]=a[l];delete a[l];l=B}if(a[l]==="hide"&&p||a[l]==="show"&&!p)return h.complete.call(this);if(n&&(l==="height"||l==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(wa(this.nodeName)==="inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[l])){(h.specialEasing=
h.specialEasing||{})[l]=a[l][1];a[l]=a[l][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(K,L){var S=new c.fx(y,h,K);if(vb.test(L))S[L==="toggle"?p?"show":"hide":L](a);else{var D=wb.exec(L),R=S.cur(true)||0;if(D){L=parseFloat(D[2]);var $=D[3]||"px";if($!=="px"){c.style(y,K,(L||1)+$);R=(L||1)/S.cur(true)*R;c.style(y,K,R+$)}if(D[1])L=(D[1]==="-="?-1:1)*L+R;S.custom(R,L,$)}else S.custom(R,L,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:da("show",1),slideUp:da("hide",1),slideToggle:da("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,e,g){return this.animate(b,d,e,g)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=
c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&
this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?a:0},custom:function(a,b,d){function e(h){return g.step(h)}this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;var g=this;a=c.fx;e.elem=this.elem;
if(e()&&c.timers.push(e)&&!La)La=setInterval(a.tick,a.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;
this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var g=this.elem,h=this.options;c.each(["","X","Y"],function(n,p){g.style["overflow"+p]=h.overflow[n]})}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var l in this.options.curAnim)c.style(this.elem,l,this.options.orig[l]);this.options.complete.call(this.elem)}return false}else{a=
b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(La);La=null},speeds:{slow:600,
fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var xb=/^t(?:able|d|h)$/i,Za=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in A.documentElement?function(a){var b=
this[0],d;if(a)return this.each(function(l){c.offset.setOffset(this,a,l)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var g=b.ownerDocument,h=g.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=g.body;g=ia(g);return{top:d.top+(g.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(g.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-
(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(B){c.offset.setOffset(this,a,B)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,e=b,g=b.ownerDocument,h,l=g.documentElement,n=g.body;e=(g=g.defaultView)?g.getComputedStyle(b,null):b.currentStyle;for(var p=b.offsetTop,y=b.offsetLeft;(b=b.parentNode)&&b!==n&&b!==l;){if(c.offset.supportsFixedPosition&&e.position==="fixed")break;
h=g?g.getComputedStyle(b,null):b.currentStyle;p-=b.scrollTop;y-=b.scrollLeft;if(b===d){p+=b.offsetTop;y+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&xb.test(b.nodeName))){p+=parseFloat(h.borderTopWidth)||0;y+=parseFloat(h.borderLeftWidth)||0}e=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&h.overflow!=="visible"){p+=parseFloat(h.borderTopWidth)||0;y+=parseFloat(h.borderLeftWidth)||0}e=h}if(e.position==="relative"||e.position==="static"){p+=
n.offsetTop;y+=n.offsetLeft}if(c.offset.supportsFixedPosition&&e.position==="fixed"){p+=Math.max(l.scrollTop,n.scrollTop);y+=Math.max(l.scrollLeft,n.scrollLeft)}return{top:p,left:y}};c.offset={initialize:function(){var a=A.body,b=A.createElement("div"),d,e,g,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;g=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==5;this.doesAddBorderForTableAndCells=g.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var g=c(a),h=g.offset(),l=c.css(a,"top"),n=c.css(a,"left"),p=e==="absolute"&&c.inArray("auto",[l,n])>-1;e={};var y={};if(p)y=g.position();l=p?y.top:parseInt(l,
10)||0;n=p?y.left:parseInt(n,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+l;if(b.left!=null)e.left=b.left-h.left+n;"using"in b?b.using.call(a,e):g.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=Za.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],
"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||A.body;a&&!Za.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var g=this[0],h;if(!g)return null;if(e!==G)return this.each(function(){if(h=ia(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=ia(g))?"pageXOffset"in
h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:g[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var g=this[0];if(!g)return e==null?null:this;if(c.isFunction(e))return this.each(function(h){var l=c(this);l[d](e.call(this,
h,l[d]()))});return c.isWindow(g)?g.document.compatMode==="CSS1Compat"&&g.document.documentElement["client"+b]||g.document.body["client"+b]:g.nodeType===9?Math.max(g.documentElement["client"+b],g.body["scroll"+b],g.documentElement["scroll"+b],g.body["offset"+b],g.documentElement["offset"+b]):e===G?parseFloat(c.css(g,d)):this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);
